#!/usr/bin/env bash
# =============================================================================
#  cloud_deploy.sh — Deploy Intern Hunter to Oracle Cloud Free Tier VM
#  Run from: ~/Desktop/agent/intern_hunter/
#  Usage:    bash cloud_deploy.sh
# =============================================================================
set -euo pipefail
IFS=$'\n\t'

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

ok()   { echo -e "${GREEN}✅  $*${RESET}"; }
warn() { echo -e "${YELLOW}⚠️   $*${RESET}"; }
err()  { echo -e "${RED}❌  $*${RESET}"; }
info() { echo -e "${CYAN}ℹ️   $*${RESET}"; }
step() { echo -e "\n${BOLD}${CYAN}━━━ $* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"; }

ENV_FILE=".env.deploy"
DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
TARBALL="/tmp/intern_hunter_deploy.tar.gz"
REMOTE_DIR="/home/ubuntu/intern_hunter"

# =============================================================================
# BANNER
# =============================================================================
echo ""
echo -e "${BOLD}${CYAN}"
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║   🚀  INTERN HUNTER — Oracle Cloud Deployment Script    ║"
echo "  ║   Deploys your agent to run 24/7, free forever          ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"

# =============================================================================
# STEP 1 — COLLECT CREDENTIALS
# =============================================================================
step "STEP 1/8 — Collect Credentials"
echo ""
echo "  I'll ask for your credentials one by one."
echo "  Passwords are hidden while you type."
echo "  Press Enter to keep an existing value shown in [brackets]."
echo ""

_load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$ENV_FILE"
    fi
}

_save_env() {
    cat > "$ENV_FILE" <<EOF
# Auto-generated by cloud_deploy.sh — contains secrets, never commit this
MISTRAL_API_KEY="${MISTRAL_API_KEY}"
GMAIL_SENDER="${GMAIL_SENDER}"
GMAIL_APP_PASSWORD="${GMAIL_APP_PASSWORD}"
COLLEGE_EMAIL="${COLLEGE_EMAIL}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}"
INTERNSHALA_EMAIL="${INTERNSHALA_EMAIL}"
INTERNSHALA_PASSWORD="${INTERNSHALA_PASSWORD}"
ORACLE_SSH_KEY_PATH="${ORACLE_SSH_KEY_PATH}"
ORACLE_VM_IP="${ORACLE_VM_IP}"
EOF
    chmod 600 "$ENV_FILE"
}

_prompt()       { local v; read -r -p "  $1: " v; echo "${v}"; }
_prompt_secret(){ local v; read -r -s -p "  $1: " v; echo ""; echo "${v}"; }
_prompt_default() {
    local label="$1" default="$2"
    local v
    read -r -p "  ${label} [${default}]: " v
    echo "${v:-$default}"
}

_load_env

echo -e "${BOLD}  ① Mistral AI API Key${RESET} (for job scoring + cover letters)"
MISTRAL_API_KEY="$(_prompt_default "Mistral API key" "${MISTRAL_API_KEY:-}")"
[[ -z "$MISTRAL_API_KEY" ]] && { err "Mistral API key is required."; exit 1; }

echo ""
echo -e "${BOLD}  ② Gmail Sender Address${RESET} (notifications sent from this address)"
GMAIL_SENDER="$(_prompt_default "Gmail address" "${GMAIL_SENDER:-}")"

echo ""
echo -e "${BOLD}  ③ Gmail App Password${RESET} (16-char, from myaccount.google.com/apppasswords)"
echo "     Leave blank to skip email notifications."
GMAIL_APP_PASSWORD="$(_prompt_secret "Gmail App Password")"
[[ -z "$GMAIL_APP_PASSWORD" && -n "${GMAIL_APP_PASSWORD:-}" ]] && GMAIL_APP_PASSWORD="${GMAIL_APP_PASSWORD}"

echo ""
echo -e "${BOLD}  ④ College Email${RESET} (HIGH PRIORITY alerts go here — your IIT Jodhpur email)"
COLLEGE_EMAIL="$(_prompt_default "College email" "${COLLEGE_EMAIL:-}")"

echo ""
echo -e "${BOLD}  ⑤ Telegram Bot Token${RESET} (optional — press Enter to skip)"
TELEGRAM_BOT_TOKEN="$(_prompt_default "Telegram bot token" "${TELEGRAM_BOT_TOKEN:-}")"

echo ""
echo -e "${BOLD}  ⑥ Telegram Chat ID${RESET} (optional — press Enter to skip)"
TELEGRAM_CHAT_ID="$(_prompt_default "Telegram chat ID" "${TELEGRAM_CHAT_ID:-}")"

echo ""
echo -e "${BOLD}  ⑦ Internshala Email${RESET} (used to log into Internshala for auto-apply)"
INTERNSHALA_EMAIL="$(_prompt_default "Internshala email" "${INTERNSHALA_EMAIL:-}")"

echo ""
echo -e "${BOLD}  ⑧ Internshala Password${RESET}"
INTERNSHALA_PASSWORD="$(_prompt_secret "Internshala password")"

echo ""
echo -e "${BOLD}  ⑨ Oracle SSH Key Path${RESET} (path to your .pem or private key file)"
ORACLE_SSH_KEY_PATH="$(_prompt_default "SSH key path" "${ORACLE_SSH_KEY_PATH:-$HOME/.ssh/id_rsa}")"
if [[ ! -f "$ORACLE_SSH_KEY_PATH" ]]; then
    warn "SSH key not found at $ORACLE_SSH_KEY_PATH — will fail at upload step."
    warn "Generate one with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/oracle_intern_hunter"
fi

echo ""
echo -e "${BOLD}  ⑩ Oracle VM Public IP${RESET} (from your Oracle Cloud Console)"
ORACLE_VM_IP="$(_prompt_default "Oracle VM public IP" "${ORACLE_VM_IP:-}")"
if [[ -z "$ORACLE_VM_IP" ]]; then
    echo ""
    warn "No Oracle VM IP provided. Printing setup instructions:"
    echo ""
    echo "  1. Go to https://cloud.oracle.com → sign in"
    echo "  2. Compute → Instances → Create Instance"
    echo "     • Shape: VM.Standard.A1.Flex (Always Free ARM)"
    echo "     • Image: Ubuntu 22.04"
    echo "     • Add your SSH public key"
    echo "  3. Copy the Public IP from the instance detail page"
    echo "  4. Re-run: bash cloud_deploy.sh"
    echo ""
    echo "  See README_ORACLE_SETUP.md for full instructions."
    exit 1
fi

_save_env
ok "Credentials saved to $ENV_FILE (chmod 600, never committed)"


# =============================================================================
# STEP 2 — ADD .GITIGNORE ENTRIES
# =============================================================================
step "STEP 2/8 — Protect Secrets"

GITIGNORE="$DEPLOY_DIR/.gitignore"
declare -a IGNORE_ENTRIES=(
    ".env.deploy"
    ".env.deploy.*"
    "config.yaml"
    "sessions/"
    "credentials/"
    "data/"
    "*.tar.gz"
    "__pycache__/"
    "*.pyc"
    ".venv/"
    "venv/"
)

touch "$GITIGNORE"
for entry in "${IGNORE_ENTRIES[@]}"; do
    if ! grep -qxF "$entry" "$GITIGNORE" 2>/dev/null; then
        echo "$entry" >> "$GITIGNORE"
    fi
done
ok ".gitignore updated — secrets are protected"


# =============================================================================
# STEP 3 — PACKAGE THE PROJECT
# =============================================================================
step "STEP 3/8 — Package Project"

info "Creating deployment tarball (excluding data/, sessions/, __pycache__)…"
cd "$(dirname "$DEPLOY_DIR")"  # go one level up to intern_hunter parent
tar -czf "$TARBALL" \
    --exclude='intern_hunter/.env*' \
    --exclude='intern_hunter/data/*' \
    --exclude='intern_hunter/sessions/*' \
    --exclude='intern_hunter/credentials/*' \
    --exclude='intern_hunter/__pycache__' \
    --exclude='intern_hunter/**/__pycache__' \
    --exclude='intern_hunter/*.pyc' \
    --exclude='intern_hunter/**/*.pyc' \
    --exclude='intern_hunter/.venv' \
    --exclude='intern_hunter/venv' \
    intern_hunter/

TARBALL_SIZE=$(du -sh "$TARBALL" | cut -f1)
ok "Package created: $TARBALL ($TARBALL_SIZE)"
cd "$DEPLOY_DIR"


# =============================================================================
# SSH HELPER
# =============================================================================
SSH_OPTS="-i ${ORACLE_SSH_KEY_PATH} -o StrictHostKeyChecking=no -o ConnectTimeout=30"
REMOTE="ubuntu@${ORACLE_VM_IP}"

_ssh() { ssh $SSH_OPTS "$REMOTE" "$@"; }
_scp() { scp $SSH_OPTS "$@"; }


# =============================================================================
# STEP 4 — TEST SSH + UPLOAD PROJECT
# =============================================================================
step "STEP 4/8 — Upload to Oracle VM"

info "Testing SSH connection to $ORACLE_VM_IP…"
if ! _ssh "echo 'SSH OK'" 2>/dev/null | grep -q "SSH OK"; then
    err "Cannot connect to $ORACLE_VM_IP. Check:"
    echo "    • VM is running (Oracle Console → Compute → Instances)"
    echo "    • SSH key path is correct: $ORACLE_SSH_KEY_PATH"
    echo "    • Port 22 is open (VCN → Security Lists → Ingress: TCP 22)"
    echo "    • Try manually: ssh -i $ORACLE_SSH_KEY_PATH ubuntu@$ORACLE_VM_IP"
    exit 1
fi
ok "SSH connection successful"

info "Uploading project to ${REMOTE}:~/ …"
_scp "$TARBALL" "${REMOTE}:~/"
ok "Upload complete"


# =============================================================================
# STEP 5 — REMOTE INSTALL
# =============================================================================
step "STEP 5/8 — Install Dependencies on VM"

info "Installing Python, pip, venv, Playwright dependencies…"
_ssh bash -s << 'REMOTE_INSTALL'
set -e
echo "==> System update"
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    python3 python3-pip python3-venv python3-dev \
    git curl wget xvfb \
    libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 \
    libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 \
    libxfixes3 libxrandr2 libgbm1 libasound2 \
    fonts-liberation libappindicator3-1 libgtk-3-0

echo "==> Extracting project"
tar -xzf ~/intern_hunter_deploy.tar.gz -C ~/
echo "==> Creating virtual environment"
cd ~/intern_hunter
python3 -m venv venv
source venv/bin/activate
echo "==> Installing Python packages"
pip install --upgrade pip -q
pip install -r requirements.txt -q
echo "==> Installing Playwright Chromium"
playwright install chromium
echo "==> Done with remote install"
REMOTE_INSTALL

ok "Dependencies installed on VM"


# =============================================================================
# STEP 6 — WRITE CONFIG.YAML ON REMOTE VM
# =============================================================================
step "STEP 6/8 — Deploy Config with Credentials"

info "Writing config.yaml on remote VM (never stored in git)…"

# We pass all credentials as env vars to the heredoc to avoid shell escaping issues
TELEGRAM_ENABLED="false"
[[ -n "$TELEGRAM_BOT_TOKEN" ]] && TELEGRAM_ENABLED="true"

ssh $SSH_OPTS "$REMOTE" bash -s <<INJECT_CONFIG
cat > ~/intern_hunter/config.yaml << 'YAML_EOF'
# ─────────────────────────────────────────────────────────────────────────────
#  Intern Hunter — Auto-generated config (cloud_deploy.sh)
#  Do NOT edit manually on server — re-run cloud_deploy.sh to update
# ─────────────────────────────────────────────────────────────────────────────

candidate:
  name: "Brijesh Thakkar"
  college: "IIT Jodhpur"
  degree: "B.Tech CSE + EE"
  year: 2
  graduation_year: 2028
  personal_email: "brijeshthakkariitian5126@gmail.com"
  college_email: "${COLLEGE_EMAIL}"
  phone: "9537474957"
  skills:
    - C++
    - Python
    - JavaScript
    - TypeScript
    - React
    - Next.js
    - FastAPI
    - Django
    - Node.js
    - TensorFlow
    - PyTorch
    - PostgreSQL
    - MongoDB
    - Redis
    - Docker
    - AWS EC2
    - Kubernetes
    - Git
    - SQL
    - REST APIs
    - GraphQL
    - Linux
    - Bash
    - Data Structures & Algorithms
  target_roles:
    - "Full Stack Intern"
    - "Backend Intern"
    - "ML/AI Intern"
    - "Software Engineer Intern"
    - "Systems Programming Intern"
    - "Research Intern (CS)"
    - "Data Science Intern"
    - "Python Developer Intern"
    - "React Developer Intern"
    - "DevOps Intern"
    - "Platform Engineering Intern"
  projects:
    - name: "SentinelDB"
      description: "High-performance distributed database with Raft consensus — handles 50k TPS"
    - name: "NeuroLearn"
      description: "Adaptive ML-powered learning platform serving 2,000+ students with personalised curricula"

preferences:
  remote_only: true
  remote_keywords:
    - "remote"
    - "wfh"
    - "work from home"
    - "anywhere in india"
    - "work from anywhere"
  min_stipend: 10000
  max_applications_per_day: 20
  min_ai_match_score: 70
  blacklist_keywords:
    - "unpaid"
    - "no stipend"
    - "equity only"
    - "part-time only"

openai:
  api_key: ""
  model: ""

gemini:
  api_key: ""
  model: ""

mistral:
  api_key: "${MISTRAL_API_KEY}"
  scoring_model: "mistral-small-latest"
  cover_letter_model: "mistral-small-latest"
  max_cover_letter_words: 150

google_drive:
  folder_id: ""
  check_interval_minutes: 30
  credentials_path: "credentials/credentials.json"
  token_path: "credentials/token.json"
  scopes:
    - "https://www.googleapis.com/auth/drive.readonly"

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  sender_address: "${GMAIL_SENDER}"
  app_password: "${GMAIL_APP_PASSWORD}"

telegram:
  enabled: ${TELEGRAM_ENABLED}
  bot_token: "${TELEGRAM_BOT_TOKEN}"
  chat_id: "${TELEGRAM_CHAT_ID}"

platforms:
  internshala:
    enabled: true
    auto_apply: true
    session_file: "sessions/internshala.json"
    base_url: "https://internshala.com/internships/work-from-home-internships/"
    search_skills:
      - react
      - python
      - backend
      - machine-learning
      - javascript
      - typescript
      - nodejs
      - django
      - fastapi
      - data-science
  linkedin:
    enabled: true
    auto_apply: true
    session_file: "sessions/linkedin.json"
    base_url: "https://www.linkedin.com/jobs/search/"
    search_skills:
      - "full stack developer"
      - "backend developer"
      - "machine learning"
      - "software engineer"
      - "python developer"
      - "react developer"
  wellfound:
    enabled: true
    auto_apply: false
    session_file: "sessions/wellfound.json"
    base_url: "https://wellfound.com/jobs"

agent:
  run_interval_hours: 6
  dry_run: false
  data_dir: "data"
  db_path: "data/agent.db"
  screenshots_dir: "data/screenshots"
  daily_digest_hour: 8
  daily_digest_minute: 0

scraping:
  min_delay_ms: 1000
  max_delay_ms: 4000
  page_timeout_ms: 45000
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
YAML_EOF
echo "Config written OK"
INJECT_CONFIG

ok "config.yaml written on remote VM (credentials injected, never in git)"


# =============================================================================
# STEP 7 — SYSTEMD SERVICE + XVFB
# =============================================================================
step "STEP 7/8 — Set Up systemd Service"

info "Creating Xvfb and intern-hunter systemd services…"
_ssh bash -s << 'REMOTE_SYSTEMD'
set -e

# ── Xvfb virtual display service ─────────────────────────────────────────────
sudo tee /etc/systemd/system/xvfb.service > /dev/null << 'EOF'
[Unit]
Description=Xvfb Virtual Display (for Playwright headless Chromium)
After=network.target

[Service]
Type=forking
User=ubuntu
ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x800x24 -ac +extension RANDR
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# ── Intern Hunter agent service ───────────────────────────────────────────────
sudo tee /etc/systemd/system/intern-hunter.service > /dev/null << 'EOF'
[Unit]
Description=Intern Hunter — Automated AI Internship Agent
After=network-online.target xvfb.service
Wants=network-online.target xvfb.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/intern_hunter
ExecStart=/home/ubuntu/intern_hunter/venv/bin/python agent.py --schedule
Restart=always
RestartSec=60
StartLimitIntervalSec=300
StartLimitBurst=5
StandardOutput=journal
StandardError=journal
Environment=DISPLAY=:99
Environment=HOME=/home/ubuntu

[Install]
WantedBy=multi-user.target
EOF

# ── Watchdog cron (belt-and-suspenders) ──────────────────────────────────────
(crontab -l 2>/dev/null; echo "*/10 * * * * systemctl is-active --quiet intern-hunter || sudo systemctl restart intern-hunter") \
    | sort -u | crontab -

# ── Reload + enable + start ──────────────────────────────────────────────────
sudo systemctl daemon-reload
sudo systemctl enable xvfb.service
sudo systemctl start xvfb.service
sleep 2
sudo systemctl enable intern-hunter.service
sudo systemctl start intern-hunter.service
sleep 3

echo "==> Service status:"
sudo systemctl status intern-hunter.service --no-pager -l || true
REMOTE_SYSTEMD

ok "systemd services created and started"


# =============================================================================
# STEP 8 — VERIFY DEPLOYMENT
# =============================================================================
step "STEP 8/8 — Verify Deployment"

info "Running quick verification on remote VM…"
echo ""

# Check service is active
SERVICE_STATUS=$(_ssh "systemctl is-active intern-hunter.service" 2>/dev/null || echo "unknown")
if [[ "$SERVICE_STATUS" == "active" ]]; then
    ok "intern-hunter.service is ACTIVE and running"
else
    warn "Service status: $SERVICE_STATUS — checking logs for errors…"
    _ssh "sudo journalctl -u intern-hunter -n 30 --no-pager" || true
fi

# Run a quick dry-run to confirm agent works
info "Running agent --dry-run on VM (first 20 lines) to confirm everything works…"
echo ""
_ssh bash -s << 'VERIFY'
cd ~/intern_hunter
source venv/bin/activate
timeout 60 python agent.py --dry-run 2>&1 | head -20 || true
VERIFY

echo ""
echo -e "${BOLD}${GREEN}"
echo "  ╔══════════════════════════════════════════════════════════════╗"
echo "  ║                                                              ║"
echo "  ║   🎉  INTERN HUNTER IS NOW LIVE ON ORACLE CLOUD!            ║"
echo "  ║                                                              ║"
echo "  ╚══════════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo ""
echo -e "${BOLD}  Your VM:${RESET}       $ORACLE_VM_IP"
echo -e "${BOLD}  SSH in:${RESET}        ssh -i $ORACLE_SSH_KEY_PATH ubuntu@$ORACLE_VM_IP"
echo ""
echo -e "${BOLD}  Management commands (run from your laptop):${RESET}"
echo "   bash remote_logs.sh          — live logs stream from cloud"
echo "   bash remote_dashboard.sh     — view dashboard stats"
echo "   bash update_agent.sh         — push code changes + restart"
echo ""
echo -e "${BOLD}  On the VM itself:${RESET}"
echo "   sudo journalctl -u intern-hunter -f     — live logs"
echo "   sudo systemctl restart intern-hunter    — restart agent"
echo "   sudo systemctl status intern-hunter     — check status"
echo "   cd intern_hunter && python dashboard.py — stats"
echo ""
echo -e "${BOLD}  Next step — set up auto-apply sessions:${RESET}"
echo "   Run: bash cloud_deploy.sh --sessions"
echo "   (logs in to Internshala locally and uploads cookies to VM)"
echo ""
warn "Google Drive resume sync requires OAuth — run it locally first:"
echo "   python setup.py  (select Google Drive step)"
echo ""
